from datetime import timedelta, datetime

# Default variables
default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2023, 12, 22),
    'email': ['enrique.urrutia@patagonia.com'],
    'phone': 0,
    'email_on_failure': True,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=60),
    'snowflake_conn_id': 'patagonia_snowflake_connection',
    'byod_erp_customer_table_name': 'CustCustomerV3Staging',
    'byod_erp_customer_table_interest_columns': [
        ('PARTYTYPE', 'STRING'),
        ('ADDRESSBOOKS', 'STRING'),
        ('ADDRESSLOCATIONROLES', 'STRING'),
        ('PRIMARYCONTACTEMAILPURPOSE', 'STRING'),
        ('ELECTRONICLOCATIONID', 'STRING'),
        ('ADDRESSCOUNTRYREGIONISOCODE', 'STRING'),
        ('ADDRESSCOUNTRYREGIONID', 'STRING'),
        ('CUSTOMERACCOUNT', 'STRING'),
        ('ORGANIZATIONNAME', 'STRING'),
        ('NAMEALIAS', 'STRING'),
        ('CUSTOMERGROUPID', 'STRING'),
        ('PERSONFIRSTNAME', 'STRING'),
        ('PERSONLASTNAME', 'STRING'),
        ('PARTYNUMBER', 'STRING'),
        ('FULLPRIMARYADDRESS', 'STRING'),
        ('ADDRESSDESCRIPTION', 'STRING'),
        ('ADDRESSZIPCODE', 'STRING'),
        ('ADDRESSCITY', 'STRING'),
        ('ADDRESSDISTRICTNAME', 'STRING'),
        ('ADDRESSLOCATIONID', 'STRING'),
        ('ADDRESSSTATE', 'STRING'),
        ('ADDRESSSTREET', 'STRING'),
        ('ADDRESSVALIDFROM', 'TIMESTAMP_NTZ'),
        ('PRIMARYCONTACTEMAIL', 'STRING'),
        ('PRIMARYCONTACTPHONE', 'STRING'),
        ('WAREHOUSEID', 'STRING'),
        ('DISCOUNTPRICEGROUPID', 'STRING'),
        ('PAYMENTTERMS', 'STRING'),
        ('PAYMENTMETHOD', 'STRING'),
        ('INVOICEACCOUNT', 'STRING'),
        ('DELIVERYMODE', 'STRING'),
        ('TAXEXEMPTNUMBER', 'STRING'),
        ('ISSALESTAXINCLUDEDINPRICES', 'INTEGER'),
        ('RECEIPTEMAIL', 'STRING'),
        ('RECEIPTOPTION', 'INTEGER'),
        ('DELIVERYADDRESSDESCRIPTION', 'STRING'),
        ('DELIVERYADDRESSCITY', 'STRING'),
        ('DELIVERYADDRESSCOUNTRYREGIONID', 'STRING'),
        ('DELIVERYADDRESSDISTRICTNAME', 'STRING'),
        ('DELIVERYADDRESSLOCATIONID', 'STRING'),
        ('DELIVERYADDRESSSTATE', 'STRING'),
        ('DELIVERYADDRESSSTREET', 'STRING'),
        ('DELIVERYADDRESSVALIDFROM', 'TIMESTAMP_NTZ'),
        ('AXXDOCTYPECODE', 'STRING'),
        ('AXXDOCTYPECODEPACKINGSLIP', 'STRING'),
        ('AXXIDNUMBERSKIPCHECK', 'INTEGER'),
        ('PRIMARYCONTACTEMAILRECORDID', 'BIGINT'),
        ('PRIMARYCONTACTPHONERECORDID', 'BIGINT'),
        ('ADDRESSRECORDID', 'BIGINT'),
        ('CREDMANCUSTOMERSINCE', 'TIMESTAMP_NTZ'),
        ('SYNCSTARTDATETIME', 'TIMESTAMP_NTZ')
    ]
}
